@baseUrl = http://localhost:3000

###GET
GET {{baseUrl}}/academicYear
Content-Type: application/json

### GET ALL ACADEMIC YEAR
GET {{baseUrl}}/academicYear/all
Content-Type: application/json
Authorization: {{adminToken}}
