@baseUrl = http://localhost:3000


### Login with default user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"admin",
  "password":"group20"
}

> {%
  client.global.set("adminToken", response.body.token);
%}