@baseUrl = http://localhost:3000
@authToken ={{adminToken}}

### Get contact wich id is 1
GET {{baseUrl}}/contacts/getOne:1
Content-Type: application/json
Authorization: {{adminToken}}

### Get all contacts
GET {{baseUrl}}/contacts/getAll
Content-Type: application/json
Authorization: {{adminToken}}

### Get all contacts by user
GET {{baseUrl}}/contacts/getByUser
Content-Type: application/json
Authorization: {{adminToken}}

### Update
PATCH {{baseUrl}}/contacts/update
Content-Type: application/json
Authorization: {{adminToken}}

{
    "idContact": 17,
    "stateContact": "pris"
}

### Add
POST {{baseUrl}}/contacts/add
Content-Type: application/json
Authorization: {{adminToken}}

{
    "enterpriseID": 3
}