@baseUrl = http://localhost:3000
@authToken ={{adminToken}}

### Get enterprise wich id is 1
GET {{baseUrl}}/enterprises/getOne:1
Content-Type: application/json
Authorization: {{adminToken}}

### Get all enterprises
GET {{baseUrl}}/enterprises/getAll
Content-Type: application/json
Authorization: {{adminToken}}

### Add a new enterprise
POST {{baseUrl}}/enterprises/add
Content-Type: application/json
Authorization: {{adminToken}}

{
    "tradeName": "Belfius",
    "designation": "Belfius designation",
    "address": "Belfius adresse",
    "email": "Belfius@email.com",
    "phoneNumber": "0123456789",
    "city": "Belfius city"

}

### Blacklist an enterprise
POST {{baseUrl}}/enterprises/blacklist
Content-Type: application/json
Authorization: {{adminToken}}

{
    "id": 1,
      "blackListed": true,
      "blackListMotivation": "Blacklist reason",
      "version": 1,
      "tradeName": "Assyst Europe",
      "address": "Avenue du Japon, 1/B9",
      "phoneNumber": "02.609.25.00",
      "city": "1420 Braine-l'Alleud"

}