@baseUrl = http://localhost:3000
@authToken = {{adminToken}}

### GET ONE INTERNSHIP BY STUDENT ID = 27
GET {{baseUrl}}/internships/getOneInternshipByStudentId:27
Authorization: {{adminToken}}

### GET ONE INTERNSHIP BY STUDENT ID < 0
GET {{baseUrl}}/internships/getOneInternshipByStudentId:-1
Authorization: {{adminToken}}

### GET ONE INTERNSHIP BY STUDENT WHO DOES NOT HAVE AN INTERNSHIP
GET {{baseUrl}}/internships/getOneInternshipByStudentId:1
Authorization: {{adminToken}}

### UPDATE INTERNSHIP SUBJECT
PATCH {{baseUrl}}/internships/updateSubject
Content-Type: application/json
Authorization: {{adminToken}}

{
    "id": 14,
    "subject": "New Subject",
    "academicYear": {
        "id": 1
    },
    "version": 2
}

### UPDATE INTERNSHIP SUBJECT WITH WRONG VERSION
PATCH {{baseUrl}}/internships/updateSubject
Content-Type: application/json
Authorization: {{adminToken}}

{
  "id": 1,
  "subject": "New Subject",
  "academicYear": 1,
  "version": 99
}

### ADD INTERNSHIP
POST {{baseUrl}}/internships/add
Content-Type: application/json
Authorization: {{adminToken}}

{
    "subject": "SubjectTEst",
    "signatureDate": "2024-01-01",
    "supervisor": {
        "id": 8
    },
    "contact": {
      "id": 39
    },
    "academicYear": {
      "id": 3
    }
}

### ADD INTERNSHIP WITH CONTACT NOT IT ACCEPTED STATE
POST {{baseUrl}}/internships/add
Content-Type: application/json
Authorization: {{adminToken}}

{
    "signatureDate": "2024-01-01",
    "supervisorId": 3,
    "contactId": 4,
    "academicYear": 1
}

### ADD INTERNSHIP WITHOUTH SIGNATURE DATE
POST {{baseUrl}}/internships/add
Content-Type: application/json
Authorization: {{adminToken}}

{
    "supervisorId": 3,
    "contactId": 4,
    "academicYear": 1
}

### ADD INTERNSHIP WITH A SUPERVISOR NOT FROM THE SAME ENTERPRISE AS THE CONTACT
POST {{baseUrl}}/internships/add
Content-Type: application/json
Authorization: {{adminToken}}

{
    "signatureDate": "2024-01-01",
    "supervisorId": 2,
    "contactId": 8,
    "academicYear": 1
}

### Get number of interships for an enterprise
GET {{baseUrl}}/internships/getNbInternships:2
Content-Type: application/json
Authorization: {{adminToken}}

### Get number of interships for an enterprise for a specific year
GET {{baseUrl}}/internships/getNbInternshipsPerAcademicYear:2:2022-2023
Content-Type: application/json
Authorization: {{adminToken}}