@baseUrl = http://localhost:3000
@authToken = {{adminToken}}

### CREATE A NEW SUPERVISOR
POST {{baseUrl}}/supervisors/add
Content-Type: application/json
Authorization: {{adminToken}}

{
  "lastName": "Supervisor",
  "firstName": "Supervisor",
  "email": "super@gmail.com",
  "enterprise": {
    "id": 3,
    "tradeName": "Infrabel",
    "designation": null,
    "address": "Rue Bara, 135",
    "phoneNumber": "02 525 22 11",
    "city": "1070 Bruxelles",
    "email": null,
    "blackListed": false,
    "blackListMotivation": null,
    "version": 1
  },
  "phoneNumber": "1234567890"
}

### CREATE A NEW SUPERVISOR WITH INVALID EMAIL THAT ALREADY EXISTS
POST {{baseUrl}}/supervisors/add
Content-Type: application/json
Authorization: {{adminToken}}

{
  "lastName": "Supervisor 1",
  "firstName": "Supervisor 1",
  "email": "f.assal@assyst-europe.com",
  "enterpriseId": 1,
  "phoneNumber": "1234567890"
}

### CREATE A NEW SUPERVISOR WITH INVALID ENTERPRISE ID
POST {{baseUrl}}/supervisors/add
Content-Type: application/json
Authorization: {{adminToken}}

{
  "lastName": "Supervisor 1",
  "firstName": "Supervisor 1",
  "email": "test2@gmail.com",
  "enterpriseId": 99,
  "phoneNumber": "1234567890"
}

### GET ALL SUPERVISORS
GET {{baseUrl}}/supervisors/getAll
Content-Type: application/json
Authorization: {{adminToken}}

### GET SUPERVISOR BY ID = 1
GET {{baseUrl}}/supervisors/getOne:1
Content-Type: application/json
Authorization: {{adminToken}}

### GET ALL SUPERVISORS BY ENTERPRISE ID = 1
GET {{baseUrl}}/supervisors/getByEnterprise:1
Content-Type: application/json
Authorization: {{adminToken}}