@baseUrl = http://localhost:3000


### LOGIN WITH ADMIN USER
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"admin",
  "password":"group20"
}

> {%
  client.global.set("adminToken", response.body.token);
%}

### LOGIN WITH STUDENT USER
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"matteo@student.vinci.be",
  "password":"group20"
}

> {%
  client.global.set("adminToken", response.body.token);
%}

### LOGIN WITH TEACHER USER
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"teodor@vinci.be",
  "password":"group20"
}

> {%
  client.global.set("adminToken", response.body.token);
%}

### Get user loged in
GET {{baseUrl}}/auths
Content-Type: application/json
Authorization: {{adminToken}}


### Get all users
GET {{baseUrl}}/auths/users
Content-Type: application/json
Authorization: {{adminToken}}



### REGISTER A NEW STUDENT USER
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "test@student.vinci.be",
  "password": "group20",
  "role": "Etudiant",
  "firstName": "Student",
  "lastName": "Vinci",
  "telephoneNumber": "0499999999"
}

### REGISTER A NEW TEACHER USER
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "test@vinci.be",
  "password": "group20",
  "role": "Professeur",
  "firstName": "Teacher",
  "lastName": "Vinci",
  "telephoneNumber": "0499999999"
}

### REGISTER A NEW ADMIN USER
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "test2@vinci.be",
  "password": "group20",
  "role": "Administratif",
  "firstName": "admin2",
  "lastName": "Vinci2",
  "telephoneNumber": "0499999955"
}

### UPDATE USER PROFILE
PUT {{baseUrl}}/auths/updateProfile
Content-Type: application/json
Authorization: {{adminToken}}

{
  "id": 12,
  "firstName": "test",
  "lastName": "test",
  "telephoneNumber": "0499999999",
  "role": "Administratif",
  "email": "admin",
  "registrationDate": "2024-04-19",
  "password": "group20",
  "version": 1
}

### GET USER BY ID
GET {{baseUrl}}/auths/user:3
Content-Type: application/json
Authorization: {{adminToken}}

### GET NUMBER OF STUDENTS WITH INTERNSHIPS IN ALL ACADEMIC YEARS
GET {{baseUrl}}/auths/studentsWithInternship
Content-Type: application/json
Authorization: {{adminToken}}

### GET NUMBER OF STUDENTS WITHOUT INTERNSHIPS IN ALL ACADEMIC YEARS
GET {{baseUrl}}/auths/studentsWithoutInternship
Content-Type: application/json
Authorization: {{adminToken}}


### GET NUMBER OF STUDENTS WITH INTERNSHIPS IN A SPECIFIC ACADEMIC YEAR
GET {{baseUrl}}/auths/studentsWithInternship:2023-2024
Content-Type: application/json
Authorization: {{adminToken}}

### GET NUMBER OF STUDENTS WITHOUT INTERNSHIPS IN A SPECIFIC ACADEMIC YEAR
GET {{baseUrl}}/auths/studentsWithoutInternship:2023-2024
Content-Type: application/json
Authorization: {{adminToken}}
